---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dev
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dev
    spec:
      containers:
      - image: barry1234/demo_project:latest
        imagePullPolicy: Always
        name: dev
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: service-dev
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: dev
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: dev
  name: ingress-2048
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: service-dev
              port:
                number: 80
